### ISSUE TITLE
clarification for relationship between the sample size in the training step and inference 

### ISSUE THREAD

**Issue by timktsang** [stefanradev93/BayesFlow#19]
Thanks for the very interesting approach for simulation based inference

I have been testing on this and just would like to ask the following:

Is it a requirement that the sample size in the training is the sample as the real data?

e.g. in the example for parameter estimation, if I use the following:

losses = trainer.simulate_and_train_offline(n_sim=10000, epochs=75, batch_size=64, n_obs=10000)

i.e. the dataset has 10000 observation

then if I simulate a dataset with size 10000 and to obtain posterior, I got some reasonable value.

but when I just use the following simulate a dataset with size 1000, I got the following true value and posterior

true_params = prior(1)
print(true_params)
x = batch_simulator(true_params,1000)
param_samples = amortizer.sample(x, 10000)
print(param_samples.mean(0))
print(param_samples.std(0))

[[1.8459227  4.879591   0.42127568 0.44341898 2.0850098 ]] : true value
[ 1.9427828 14.766885  12.579591  -0.948793   1.0707246] : posterior mean
[ 0.9751236 18.545668   8.544211   0.651906   1.5197684] : posterior sd

Thank you.

**Comment by stefanradev93** [comment]
Hey Tim, if the `n_obs` is expected to vary during inference, I suggest you use online training with variable `n_obs` (i.e., passing a random function for `n_obs`). Otherwise your `n_obs` during training should be aligned with the `n_obs` during inference, especially if you expect huge difference (in your example less than a factor of 10).

**Comment by timktsang** [comment]
Thank you for your quick response!
