### ISSUE TITLE
posterior mean outside the domain of parameter

### ISSUE THREAD

**Issue by timktsang** [stefanradev93/BayesFlow#27]
Hi Stefan,

I am testing some models, however, I found that the prior of a parameter is Uniform (0.1, 0.9). but for a real data set, for one parameter the posterior mean is -0.6 and posterior sd is 0.03, may I ask how is that possible and any way we can solve it? e.g. this is a probability parameter so I use logistic transformation?

Thank you.

Best
Tim

**Comment by stefanradev93** [comment]
If the network performs well on simulated data, this probably means that your model is misspecified, i.e., the data set differs considerably than what the network has seen during simulation-based training (see https://arxiv.org/abs/2112.08866)

If you still want to do model-based predictions with the misspecified model, I suggest you estimate an unconstrained parameter, e.g. `p = sigmoid(z)`, where you estimate `z` instead of `p`.

**Comment by timktsang** [comment]
thanks for the suggestions. I tried this and it seems better.

One follow-up question I found is that if I can the format of input data, the results could change, may I ask if it is normal.

in brief, the data is in X(t), Y(t), firstly I put is as X(1),Y(1),X(2),Y(2),.. and so on, which is a 1X(36*2) matrix
I changed to 36X2 matrix  and it seems the result is more reasonable.

Thank you.

**Comment by stefanradev93** [comment]
Yes, the structure of the data (e.g., summarized or row, standardized or unstandardized, etc.) as well as the architecture of the summary network may affect performance.
