### ISSUE TITLE
Guidelines on number of output and hidden units in LSTM

### ISSUE THREAD

**Issue by yannikschaelte** [stefanradev93/BayesFlow#51]
Scenario: Using an LSTM as summary network for uni-/multivariate time series data, with a flexible number of time series steps.

Can you give recommendations on the number of output units (`summary_dim` in https://github.com/stefanradev93/BayesFlow/blob/master/bayesflow/summary_networks.py#L123, default=10) and dimension of the LSTM hidden space (`lstm_units`, default=128)?

I would guess that `summary_dim` should be >= number of parameters to make sure enough information can be preserved. `lstm_units` has here the task of summarizing the entire sequence prior to passing through the final dense network (arguably a slightly different task than in e.g. machine translation tasks), therefore it should be fairly large too?

**Comment by stefanradev93** [comment]
Hi Yannik,

assuming the posterior is nice (i.e., identifiable, no degeneracy, no dependencies), I would go with you and say that `summary_dim` should be at least the number of free model parameters. However, you may want to use more summary dimensions to give the networks more degrees of freedom during optimization.

We have some hints that _overcomplete_ summary spaces lead to more fragile inference in the presence of outliers (i.e., model misspecification): https://arxiv.org/abs/2112.08866. Using the additional MMD criterion, you can also apply PCA to the summary network outputs after optimization to see whether you have used more summary stats than necessary (Fig. 10) or how the summary stats relate to the parameters (Fig. 9).

Regarding `lstm_units`, I would keep it relatively large, since it contains the representation of the whole time series, as you have indicated.

Let me know what works for you or if you need more details.

Cheers,
Stefan

**Comment by yannikschaelte** [comment]
Hi Stefan,

thanks for the information! The discussion on the `summary_dim` makes perfectly sense. We may want to incorporate the PCA checks.

Do you have any more specific tips for `lstm_units`, have you explored values other than 128? I guess it should be at least on the order of the (expected/maximum) number of data points? But maybe just something to experiment with a bit.

Thanks,
Yannik

**Comment by stefanradev93** [comment]
I guess the optimal choice for `lstm_units` will depend on the complexity of the time series and the necessary information to be extracted for posterior inference (e.g., simple moments vs. multi-scale oscillatory parameters). For the time series models I have worked with, values between `128` and `512` used to produce rather robust results, with larger values not hurting performance, but I am not certain how well my experience generalizes to unknown models. It is definitely a parameter to juice up if initial results do not look splendid! 

Note: For really long time series, attention-based architectures may be a better choice than recurrent nets altogether.
